### PR TITLE
fix: editor restructure

### PR DESCRIPTION
**Pull request by Pho3niX90**
fixes: #450

### CODE REVIEW

**Comment by Pho3niX90** [comment]
@slipx06 can you see if this fixes the issue for you? tested it on android and chrome on my side. Just make sure the popups are working as they should

**Comment by slipx06** [comment]
Thanks but still not working for me. Tested in Edge and Chrome

**Comment by slipx06** [comment]
First popup is what should happen using a different card. Second is the issue with this card

popup

**Comment by Pho3niX90** [comment]
@slipx06 okay this is a strange one. from what I can tell, something is happening in the dom that is causing this behaviors, if I open a popup, close it with X, open another popup, close it, it all works. That being said, I can only reproduce this on my android device, in the companion app, it's not doing it for me on chrome windows, or chrome android.

I suspect that the animations are perhaps causing some race condition for the dom events, or perhaps some event leaking happening. 

I am not near my PC to emulate the webview, I will be back on Wednesday then I will be able to properly diagnose the issue.

**Comment by slipx06** [comment]
@Pho3niX90  I pushed a fix to main branch. Seems to work for me can you please check as well.

**Comment by Pho3niX90** [comment]
@slipx06 that seems to have fixed it for me on the companion app as well

**Comment by Pho3niX90** [comment]
Strangly, its happening now in the chrome browser for me :/

**Comment by slipx06** [comment]
Yup still not working

**Comment by Pho3niX90** [comment]
> @Pho3niX90 I pushed a fix to main branch. Seems to work for me can you please check as well. On further testing it might not be. If i comment out the block below it goes away
> 
> ```
> try {
>     customElements.define("content-card-editor", SunSynkCardEditor);
> } catch (_e) {
> }
> ```

okay let me revisit this implementation. as that was a nasty workaround

**Comment by Pho3niX90** [comment]
@slipx06 can you see how this acts on your system. I have combined your changes, along with cleanup of the config. thusfar it seems promising.

**Comment by slipx06** [comment]
@Pho3niX90 thanks so much for working on this. Seems to be working great. Want to test it without my changes as they may not be needed

**Comment by floschad** [comment]
> Tested and working in chrome, firefox, edge and companion app 🎆

It works, thanks for the great work!

**Pull request merged**
