### PR TITLE
Bugfix/175

### PR DESCRIPTION
**Pull request by Pho3niX90**
Fixes for the recent introduced bugs

### CODE REVIEW

**Comment by slipx06** [comment]
Still not resolved in my test

**Comment by slipx06** [comment]
Its setting them to 0
```
        let grid_voltage = state_grid_voltage ? this.toNum(state_grid_voltage.state) : null;
        let battery_current_direction = state_battery_current_direction ? parseInt(state_battery_current_direction.state) : null;
        console.log(`grid_voltage: ${grid_voltage}`);
        console.log(`battery_current_direction: ${battery_current_direction}`);
```

grid_voltage: 0
battery_current_direction: 0

**Comment by slipx06** [comment]
It returns the default value of 0 when undefined

```
    getEntity(entity: keyof CardConfigEntities, defaultValue: Partial<HassEntity> = {
        state: '0', attributes: {unit_of_measurement: ''},
    }): Partial<HassEntity & { state: any }> {
        const entityString = this._config.entities[entity];
        const state = entityString ? this.hass.states[entityString] : undefined;
        return state !== undefined ? state : defaultValue;
    }
```

**Comment by Pho3niX90** [comment]
I added another commit, just waiting for it to update this side. It seems it's the way the default value was applied to undefined. It should definitely be fixed now.

**Comment by slipx06** [comment]
Confirmed working. Thank you

**Pull request merged**
