### PR TITLE
feat: Essential icon: show solar colour from top down

### LINKED ISSUE #42: Autarky/Ratio issues
Hi @slipx06
Using the latest avaliable version of your card still notice some issues
The value can't be negative and can't exceed 100%

Can you please check?

some information:
https://www.npro.energy/main/en/help/self-sufficiency-rate

IMG_20230621_111955_474

### LINKED ISSUE #428: Essential icon: show solar colour from top down
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when grid and PV supplying power to essential load the solar colour shows below the grid colour

### Expected behaviour

show the solar colour from the top down

### Possible Solutions

will submit a commit

### Mode

Both

### Context / Reason

solar from the sky;)

### PR DESCRIPTION
**Pull request by RhysMcW**
## Description
Amend the linearGradient calculations to show the solar colour from the top down

## Related issues
closes #428

## Motivation and Context
Solar is from above, so show the solar colour frmo the top down.

## How has this been tested
built a copy of sunsynk-power-flow-card.js and installed it on my HA box and checked display of essential icon.

## Type of change
- [ ] New feature (non-breaking change which adds functionality)

## Checklist
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules
- [x ] I have updated the version in `package.json` following [semver](https://semver.org/)

### CODE REVIEW

**Comment by slipx06** [comment]
@RhysMcW I've made some changes to the logic on the compact card. Some of the checks were redundant. Can you please test.

**Comment by RhysMcW** [comment]
@slipx06, thanks, have built a new dist file and applied it to my HA - will have to wait until the morning, when I get PV again, to check

**Comment by RhysMcW** [comment]
looks good this morning
ess icon - pv from top 3

**Comment by slipx06** [comment]
It's not working properly for me 

image

**Comment by slipx06** [comment]
@RhysMcW thanks for the help with this. I've decided to simplify the logic and implement this slightly differently. Closing this pull request. This will be added to v4.37.0

**Pull request closed without merging**
