### PR TITLE
Huawei Example Configs - Update v0.2

### PR DESCRIPTION
**Pull request by Roving-Ronin**
## Description
Added examples of the card yaml that can be used by Huawei / iStore users, allowing copy and paste to configure the card, with limited editing required (i.e. just tweak solar --> max_power:  to reflect your actual setup. Also example AUX / Non-Essential devices and groups created.
Just needing to add in some example yaml files that use the energy_meter integration to automatically create the Energy Meters (i.e. utility meters, but with sensors for costs, pulled from tariff plans in the yaml) that the card then uses for the Imported from Grid / Exported to Grid / AUX and Non-Essential Daily kWh used display,

## Motivation and Context

Add support for users of Huawei (and iStore in Australia) inverters and LUNA batteries

## How has this been tested

Testing with a 2 x M1 6kW 3 phase inverter site (no battery) and 2 x L1 5kW 1 phase inverter with 1 x 15kWh LUNA battery site.

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have updated the version in `package.json` following [semver](https://semver.org/)

### CODE REVIEW

**Comment by slipx06** [comment]
Can you remove the README

**Comment by Roving-Ronin** [comment]
@slipx06 Oops. Edited after submitting but seems github keeps adding them to the request. Any idea how to fix, instead of a 'don't pull' option on the file, as best as I can work out I need to revert the README.md back to how it was, which I have done (copied current contents of yours back in), 

Looking at the Pull and it now shows only 5 files that have changed, with README.md not being one of them.

Would you have any idea of how I can edit the readme.md file and keep it seperate from yours / not have it merge when I submit a pull request?

**Comment by slipx06** [comment]
You would need more than one branch in your repository. Once branch for the pull request and another that you are using for development and the custom README.

**Comment by Roving-Ronin** [comment]
Is this OL to merge now? Following this I'll create the branch(es) on my side.

**Comment by Roving-Ronin** [comment]
No thank you ! Hopefully this makes it easy with 80-90% of the work done for Huawei / iStore inverter users to rapidly get started.

Now we just need that 'wide' card option to allow showing multiple batteries and inverters ;-) LoL.

Will update with electricity / tariff plans as people ask how they can support their setup. 

Just noticed the banner updated with the & LUNA Batteries, might be to remove that to follow the format of other inverters names in the Examples Doco.

**Pull request merged**
