### PR TITLE
localize days, hrs and min

### PR DESCRIPTION
**Pull request by svenopdehipt**
localize days, hrs and min

### CODE REVIEW

**Comment by slipx06** [comment]
Thanks. I made some small changes to further abbreviate some of the translations

**Comment by svenopdehipt** [comment]
Tage, Std and Min should be capitalized in German.

**Comment by slipx06** [comment]
ok

**Comment by svenopdehipt** [comment]
Would be nice if you could change this. I did write the capitalized but you converted them to lowercase. Could you please write them as I did or should I create a new merge request for this?

**Comment by slipx06** [comment]
Hi. No need to create a new pull request. I've already updated the local code and will include this change in the next release.

**Comment by slipx06** [comment]
fixed in 3.5.1

**Pull request merged**
