### PR TITLE
Feature/UI config

### LINKED ISSUE #162: CSS and Configuration options
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Absolutely adore the card... it has many if not most of the feature that a end-user could desire, however currently I was unable to  a way to style the card using CSS. I am working on a configuration menu that involves a few input_select and a few input_text options to aid in the configuration of the card.... Have most of the templating done to take W to kWh, added utility meters to track daily and monthly totals. However am currently unable to utilize the values of the afore mentioned within the top layer inputs

eg.
cardstyle: lite

Where lite would be a variable selected from an input_select

Oh before I forget... There was another item that caught my eye, there seems to be no ability to hide the degree symbol if there is no temperature input for the battery

### Expected behaviour

Manipulation of the the card using CSS or the ability to make the background transparent by any means that you find the easiest to implement... a solution to adding variables to the front-end, front-most options.

Attempted to input the state of my input_select sensor for my custom entity with no avail

cardstyle: |-
        {{ states["input_select.energy_db_card_style"].state }}

 The rest I can take care of, then finally the ability to hide the temperature input of the battery if none is provided

### Possible Solutions

The card-mod HACS feature by Tomas Loven would involve adding the ha-card class to the card, however this could potentially open a whole new can of worms. Look into the config template card  by Ian Richardson '@IANTRICH'.

Am definitely not the strongest coder but if there is anything that I can assist with please let me know

### Mode

Both

### Context / Reason

The whole Home Assistant environment is moving to the front-end having a way to manipulate the options for the card from there would make it allot more accessible, easier to use and almost universal ( It is almost already exactly that provided you provide the correct sensors with relevant information )

### PR DESCRIPTION
**Pull request by Pho3niX90**
Provides a UI for the cards configuration.

Just need 4 eyes to make sure I did not miss any sensors

## Related issues
fixes #162 

## Type of change
- [X] New feature (non-breaking change which adds functionality)

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] Any dependent changes have been merged and published in downstream modules
- [X] I have updated the version in `package.json` following [semver](https://semver.org/)

### CODE REVIEW

**Comment by slipx06** [comment]
Thank you 🚀🚀🚀🚀. Will take a look

**Comment by slipx06** [comment]
Do you also get this when you compile
image

**Comment by slipx06** [comment]
I cant get the color picker to work so we might need to replace with a text box unless you can figure it out. I've also added a few more entities to the config. Before I continue just wanted to confirm that my approach to adjust layout is correct? Is there perhaps a better way? Also is it possible to add dividers or free text to denote the different sections i.e. Battery, Solar etc

**Comment by Pho3niX90** [comment]
I have made them expandable to save space as a user moves along with the settings:
image

I changed the colour from rgb to ui as well, which now works, and gives the user a list of colours
image

As for the warning when compiling, this seems to be a rollup thing, if the bundle doesn't break, it's save to ignore, so I added a property in the rollup.config.mjs to ignore it

**Comment by Pho3niX90** [comment]
I changed the type back to color_rgb and introduced a helper. the color_ui was only partially working it seems.

**Comment by slipx06** [comment]
This is coming along nicely. I'm working through the section. left with Load , Grid and entities. Not sure how the device class filtering is meant to work?

**Comment by Pho3niX90** [comment]
So the device class is only suppose to limit the selectable entities from the dropdown, with those specific classes. 

Example: temperature, will only bring back temperature sensors, which would be what we want for example dc_transformer_temp_90

Filters that are supported are:

- domain
- device_class
- supported_features
- integration

The latter filter might even be useful for auto populating the the entities from known integrations.

**Comment by devilliersjohnny** [comment]
Geez... You guys seem to have blown my attempts out of the water! Question... You folks seem to have an auto populating feature, will we be able to self select an entity that is not part of the integrated models yet? Well if they have the correct unit of measurement?

**Comment by Pho3niX90** [comment]
> Geez... You guys seem to have blown my attempts out of the water! Question... You folks seem to have an auto populating feature, will we be able to self select an entity that is not part of the integrated models yet? Well if they have the correct unit of measurement?

Auto populating is not in yet, maybe at a later stage, so everything is still 100% customizable

**Comment by Pho3niX90** [comment]
@slipx06 I tested on my side now as well, the sub grouping helps a lot, I think my card is better setup now than before :)

Being able to see everything, and populating them, and seeing the effect real-time helps greatly.

**Pull request merged**
