### PR TITLE
Refactor state access to improve efficiency and maintainability

### PR DESCRIPTION
**Pull request by Pho3niX90**
The 'getState' function in the codebase has been replaced with 'getEntity', making the code more efficient and easier to maintain. This update removes the need to declare attributes for each state access, thereby reducing redundancy and enhancing the clarity of the code.

Also removed the redundant stringify and parse on line 4664 

This on it's own probably doesn't need a release, as it's just cleanup.

### CODE REVIEW

**Comment by slipx06** [comment]
@Pho3niX90  There seems to be a problem with the getEntity update.  Its not recognizing the updatied grid connected status on the card. There were no other code changes related to this

image

image

**Comment by slipx06** [comment]
Yes it is. I haven't had a chance to look into it. But it seems that some of the state changes are not being updated in the card

**Comment by Pho3niX90** [comment]
Okay will have a look at it quickly

**Comment by slipx06** [comment]
Seems like it is setting grid_status to off. Must be related to this
```
        if (grid_voltage != null && !Number.isNaN(grid_voltage)) {
            // the grid voltage can sometimes read decimals like 0.1, in cases where there is power trickled back.
            grid_status = grid_voltage > 50 ? 'on' : 'off';
        }
```

**Comment by slipx06** [comment]
```
let grid_voltage = state_grid_voltage ? this.toNum(state_grid_voltage.state) : null;
let battery_current_direction = state_battery_current_direction ? parseInt(state_battery_current_direction.state) : null;
```

Its not setting these to null anymore

**Comment by Pho3niX90** [comment]
I found the same, made a PR here -> #177  if you can just test that js with the sunsynk please. But setting it to null on my side seems to suggest that it's fine.

**Pull request merged**
